### ISSUE TITLE
Unable to compile project

### ISSUE THREAD

**Issue by FrostedGeulleisia** [TheG-Meister/pkc-mms-rando#1]
Sorry if this sounds a bit dumb of me, but I'm still new to the language (only really worked with it in the context of UPR-ZX before), however upon trying to compile I get one of two errors:

Either it fails because it can't find the `com.gmeister.temp.maps:maps:jar:0.0.1-SNAPSHOT` artifact, or can't find the `com.gmeister.temp.maps` package, I did get the Maven script working and am using the correct JDK version for sure.

The project also seems to reference files that aren't in the repo, specifically the map tile randomization part. (though I only really want to get warp, music pointer, sfx pointer and script randomization to work, to see how it all plays like and if these options are enjoyable in their current form).

I'm not sure what I'm doing wrong, maybe there's a hardcoded filepath I didn't notice, though the notes aren't exactly clear.

**Comment by TheG-Meister** [comment]
Hey no worries, all of this is on me. I've been prioritising new features over user accessibility, so it's no wonder you hit some errors.

Both of those failures are to do with me including some code I made for another project - https://github.com/TheG-Meister/render-maps. The only class that uses this code is BooleanMapGenerators.java, however, which generates simple shapes in the context of editing overworld maps. This code has long been out of date and out of scope, so I'll deprecate it and keep a copy on my local computer. I can always reimplement it when it becomes relevant again. I have some time tonight so I'll tidy that one up.

I do have some hard coded file paths in there too, hence why it requires recompilation. I'll think about that down the line, but I have some ideas in mind.

**Comment by FrostedGeulleisia** [comment]
After a bit of work, including tinkering with the environment and modifying the pom to force maven's "source" and "target" to be 1.8, I got it to successfully build..... though it appears to not be doing anything, unless I'm supposed to run it with some parameters. I run it, nothing happens, I check the pokecrystal copy - no changes there either, I assume that's not intended behavior, right?

(It took me a while as I've never actually dealt with Maven before whatsoever, this was the first time I even heard of the thing).

**Comment by TheG-Meister** [comment]
If you managed to actually run the compiled project it should have immediately thrown an error because of the hard-coded file paths. Have you modified any of the Java code?

The whole maven aspect should be irrelevant in the latest commit; I published some changes that removed the dependency a little earlier. What commit are you on?

No worries on the timing - we're coming at this from very different angles and with very different skillsets. We'll find a way to get it up and running for you eventually.

**Comment by FrostedGeulleisia** [comment]
> If you managed to actually run the compiled project it should have immediately thrown an error because of the hard-coded file paths. Have you modified any of the Java code?

I've modified exclusively the input and output file paths in Notes.java, so it points to my copy of pokecrystal. The paths that are left in there by default aren't exactly clear.

> The whole maven aspect should be irrelevant in the latest commit; I published some changes that removed the dependency a little earlier. What commit are you on?

The latest, it still kept failing to build unless I explicitly made it go through the maven script, which by itself was complaining about the defined, source option no longer being supported, and that 7 should be used instead of 5. Trying to modify the language level from the IDE itself resulted in nothing.

**Comment by TheG-Meister** [comment]
Well that sounds like a nightmare. I'll download the code on my laptop tomorrow and hopefully I can spot some similar issues.

In addition, I realised I can probably throw together a really basic command line jar that can run some of the prefab randomisers I already have set up. I don't know why I didn't think of that one earlier. At least it gives options.

**Comment by TheG-Meister** [comment]
Nice, I'm glad you're getting somewhere.

You've mentioned building a few times, what do you mean by that? Are you running it or trying to turn the code into a jar? Just wanted to make sure we're on the same page.

It could very well be that newer pokecrystal versions have changed formats. I've been pretty religiously working with dabomstew's pokecrystal-speedchoice, which hasn't been updated in a while now. Could you copy-paste the stack trace of the error?

> I don't want to clog up and potentially cause conflicts on my host

For reference, if you download the JDK using the second link, you can hide it away neatly in a folder somewhere without it being installed, and then point eclipse to it using the "Add JRE" option I mentioned in the wiki. That should be conflict-less.

**Comment by FrostedGeulleisia** [comment]
Sorry, I've been busy for the past couple days. Here's the stack trace you wanted.
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "const_value - 1"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:660)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at com.gmeister.temp.pkcmmsrando.io.DisassemblyReader.importConstants(DisassemblyReader.java:474)
	at com.gmeister.temp.pkcmmsrando.io.DisassemblyReader.readMaps(DisassemblyReader.java:275)
	at com.gmeister.temp.pkcmmsrando.Notes.randomiseWarpAreas(Notes.java:120)
	at com.gmeister.temp.pkcmmsrando.Notes.main(Notes.java:459)
```
Hence why I think it might just be a newer pokecrystal change, I've not been following that closely though.

By "building it a few times" i meant running the task, sorry I could have mixed up the terminology.

**Comment by FrostedGeulleisia** [comment]
> If you open com.gmeister.temp.pkcmmsrando.io.DisassemblyReader, and scroll to line 474, does it say else if (args[1].equals("const_value - 1")) value = count - 1;?

Yes.

>Are you setting the input and output folders to different locations?

Yes, though the input folder is technically on a network share with full read/write access (It does work, though), see below.

> And I assume you're inputting "true" for all three randomisers?

And yes, and the music/sfx pointer ones finish and output successfully.

And I am on the exact same commit.
![obraz](https://user-images.githubusercontent.com/27410260/137164940-ba278d3e-b959-43e0-8870-5b4a2f6aa5e7.png)

**Comment by TheG-Meister** [comment]
I managed to replicate the error and the problems when my newly-imported project didn't have the right JRE. Even without the red exclamation point, this seems to be typical of build path errors. Could you try the "Setting up pkc-mms-rando with the JDK" step in the wiki again?

**Comment by FrostedGeulleisia** [comment]
Alright, I did just that and turns out everything magically works now! Even with vanilla pokecrystal!
Looks like Eclipse by default set itself to the wrong JDK version (SE-14 instead of SE-15) and I just never noticed. I guess this particular issue's now resolved. Eagerly waiting for full entrance randomization so we can make it a "fun" (depends on what you consider as fun) or at least interesting challenge, while still being beatable.
An idea could be to have a toggle for scaling wild/trainer/static levels to the badge count you're supposed to have, or at the very least making sure you need all 8 Johto badges before entering the Elite Four and all 8 Kanto badges to access Red's chamber in Mt. Silver, and either moving starter selection into the player's house, making said house exit to Elm's Lab, or just not randomizing New Bark Town altogether. I have a few ideas on how that could be handled, but that probably deserves another issue (GitHub doesn't really have any other way of starting a thread).
